apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - image: localhost:5000/hello:latest
          ports:
            - containerPort: 8080
          env:
            - name: TENANT_ID
              value: "demo-tenant"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
